dqn:
  env: MountainCar-v0
  run: DQN
  stop:
    timesteps_total: 50000000
  checkpoint_config:
    checkpoint_at_end: true
  local_dir: ~/projects/reinforcement-learning/mountain_car
  config:
    num_gpus: 1
    num_workers: 15
    num_envs_per_worker: 5
    eager_tracing: true
    framework:
      grid_search:
        - tf
        - tfe
        - tf2
        - torch