a2c:
  env: CartPole-v1
  run: A2C
  stop:
    timesteps_total: 25000000
  checkpoint_config:
    checkpoint_at_end: true
  local_dir: ~/projects/reinforcement-learning/cartpole
  config:
    num_gpus: 1
    num_workers: 15
    num_envs_per_worker: 5
    framework:
      grid_search:
        - tf
        - tfe
        - tf2
        - torch