a2c:
  env: ALE/Pong-v5
  run: A2C
  stop:
    timesteps_total: 10000000
  checkpoint_config:
    checkpoint_at_end: true
  local_dir: ~/projects/reinforcement-learning/pong
  config:
    num_gpus: 1
    num_workers: 4
    num_envs_per_worker: 5
    eager_tracing: true
    framework:
      grid_search:
        - tf
        - tfe
        - tf2
        - torch